# Generated by Django 5.0.1 on 2024-01-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment'},
        ),
    ]
