# Generated by Django 5.0.1 on 2024-01-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_alter_client_options_alter_operator_options_and_more'),
        ('payments', '0003_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operators.client'),
        ),
    ]
