# Generated by Django 5.0.1 on 2024-01-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name_plural': 'Operator'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
    ]
