# Generated by Django 5.0.1 on 2024-01-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcategory',
            options={'verbose_name_plural': 'Car Category'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Driver'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sms_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
